### ISSUE TITLE
Unattended installation fails

### ISSUE THREAD

**Issue by absolutejam** [VirtualEngine/Lability#109]
Hey guys,

I noticed I was getting an error in the unattended installation process of my 2012 R2 VMs so I downloaded the 'dev' branch and removed/re-imported the module, but I'm still getting the following issue:

![unattenderror](https://cloud.githubusercontent.com/assets/6817942/15171702/8b63d062-1748-11e6-82c5-9a5ed11a5e3f.PNG)

```
PS C:\Users\james> New-LabVM -Name 'Installer Test' -MediaId 2012R2_x64_Datacenter_EN_V5_Eval | start-vm

PS C:\Users\james> Get-LabVMDefault

StartupMemory            : 2147483648
MinimumMemory            : 2147483648
MaximumMemory            : 3758096384
ProcessorCount           : 2
SwitchName               : LAB-External
Media                    : 2012R2_x64_Datacenter_EN_V5_Eval
TimeZone                 : UTC
UILanguage               : en-US
SystemLocale             : en-GB
InputLocale              : 0809:00000809
UserLocale               : en-GB
RegisteredOwner          : Lability
RegisteredOrganization   : Virtual Engine
ClientCertificatePath    : C:\ProgramData\Lability\Certificates\LabClient.pfx
RootCertificatePath      : C:\ProgramData\Lability\Certificates\LabRoot.cer
BootDelay                : 0
CustomBootstrapOrder     : MediaFirst
SecureBoot               : True
GuestIntegrationServices : False

PS C:\Users\james> Get-LabHostDefault

ConfigurationPath       : C:\Lability\Configurations
DifferencingVhdPath     : C:\Lability\VMVirtualHardDisks
HotfixPath              : C:\Lability\Hotfixes
IsoPath                 : C:\Lability\ISOs
ParentVhdPath           : C:\Lability\MasterVirtualHardDisks
ResourcePath            : C:\Lability\Resources
ResourceShareName       : Resources
DisableLocalFileCaching : False
EnableCallStackLogging  : False
```

Any ideas?

Cheers.

**Comment by iainbrighton** [comment]
Hi James - can you grab the \Windows\System32\Sysprep\Unattend.xml file from the VHDX? Thanks!

**Comment by absolutejam** [comment]
Sorry, user error!

I had a space in the VM name so that was the issue. Perhaps this needs validating before going ahead?

Thanks for your continual help @iainbrighton.

**Comment by iainbrighton** [comment]
@absolutejam Users eh?! However, it's probably a good idea to check for a valid computer name..

**Comment by tournevixx** [comment]
I am sorry if this is not the right place to share my experience with Lability but I recently struggled for 2 days due to en error thrown during unattended installation:

"Windows could not parse or process the unattend answer file for pass [specialize]. The answer file is invalid."

The root cause was that the NodeName that I set in my lab configuration file exceeded 15 characters. Although, this might be obvious for others, it wasn't for me. I am sharing this information here because Lability uses the NodeName values as ComputerName when generating the unattend.xml answer file. Maybe some stronger validation could be done and maybe also a few words where NodeName is documented.

I hope others will find my comment useful. Cheers!
