### ISSUE TITLE
Investigate Nano Server Host Support

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#154]
Now that Server 2016 is GA, it would be nice to be able to run Lability on a Nano Server host. This won't be easy, but I thought I'd put the idea out there.
- Is there any need at this moment in time?
- Is it too soon, too immature? 
- The most obvious use case that I can see is nested Hyper-V/Nano Server and integration testing - do you need an AD for integration testing anyone?!

**Comment by janegilring** [comment]
Given that Nano is now longer supported as a Hyper-V host from RS3, I suppose this issue isn' t applicable any more. A different question might be whether support for Windows Server 2016 Core should be added or if it makes no sense spending time on it since this module is primarily intended for running on Windows 10 for lab purposes (not production systems running Server).

**Comment by iainbrighton** [comment]
@janegilring Yeah - it's a shame that MS have dropped the infrastructure roles for Nano server. Maybe they'll reintroduce them in the not-too-distant future?! Until then, I'll close the issue.

**Comment by iainbrighton** [comment]
@janegilring And just to reiterate, it should work on Server Core as that's where we use it for dev and in our CI pipeline..
