### ISSUE TITLE
Cant figure out how to run setup.exe

### ISSUE THREAD

**Issue by andlo** [VirtualEngine/Lability#168]
I want to setup a NAV servef, and did figure out how to get Lability to do a lot of good work. But my NAV server will not as I will....
It never runs the setup.exe defined in the package.
So I am dooing something wrong - but what?

In my .psd1
```
  @{
      NodeName          = 'NAV2016'
      IPAddress         = '10.0.0.15'
      Role              = 'NAV2016'
      Lability_Resource = @('NAV2016')
      Lability_Media    = '2016_x64_Standard_EN_Eval'
    }
      Resource          = @(
        @{
          Id              = 'NAV2016'
          FileName        = 'en-001_microsoft_dynamics_nav_2016_x64_7053002.zip'
          Expand          = $true
          DestinationPath = '\INSTALL\NAV2016'
        }
      )
```

In my .ps1

```
  node $AllNodes.Where({
      $_.Role -in 'NAV2016'
  }).NodeName {
    ## Flip credential into username@domain.com
    $upn = '{0}@{1}' -f $Credential.UserName, $node.DomainName
    $domainCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ($upn, $Credential.Password)
 
    Package NAV2016
    {
        Ensure = "Present"
        Name = "en-001_microsoft_dynamics_nav_2016_x64_7053002"
        Path = "C:\INSTALL\NAV2016\setup.exe"
        Credential = $domainCredential
        Arguments = '/quiet /config C:\INSTALL\NAV2016\NAV2016DEMO.xml /log C:\INSTALL\NAV2016.log' # args for silent mode
    }
} 

```

**Comment by iainbrighton** [comment]
@andlo Thanks for trying Labililty out! I have a few questions that will hopefully help pinpoint where the problem is:

* After the VM is deployed, has Lability expanded the .zip file into the `C:\Install\NAV2016`  folder correctly?
* If so, what happens if you apply the .mof file/configuration manually?
* It looks like there is no $node.DomainName defined (but you may have just left it out of the example)?

I think the `Package` resource only uses the credential to access the file; if the credential is incorrect then this won't work. You _might_ want to try/need to remove the `Credential` property as the file is local to the VM anyway.

**Comment by andlo** [comment]
Yes the zip is expanded. 

I dont know how to apply the .mof manually - I am a noob ;) 

I think I have tried whith and whitout credentials. And Yes I did leave out parts og the files - and have a $node.DomaineName defined.
The VM is starting fine, and is joiend domaine and files expanded. Only thing i cant get working is starting the setup....

**Comment by andlo** [comment]
OHHHH - that did some of it - now setup is running. So now my problems is "only" about setting up the NAV :) 

Thanks
