### ISSUE TITLE
VHDX media with Generation 1 VMs

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#194]
It looks like it's assumed/hard-coded that Lability always creates a Gen1 VM for VHD media and a Gen2 VM for VHDX media?

Is there any way to override the default behaviour and create a Gen1 VM using VHDX media? __Gen2 VMs only support VHDX media.__

**Comment by rikhepworth** [comment]
@iainbrighton , this should be the other way around - create Generation 2 VMs with VHD media

**Comment by iainbrighton** [comment]
@rikhepworth I thought Gen 2 VMs __only__ supported VHDX files?

**Comment by rikhepworth** [comment]
Ah yes, my bad. :(

**Comment by rikhepworth** [comment]
My testing shows that the original fault we encountered, where using VHD media as the source for a new VM resulted in an error because lability seemed to think it had created a vhdx file for the new machine appears to be fixed. @iainbrighton I'm assuming this issue is related to that fault as well, since I couldn't find another that talked about that one.

**Comment by iainbrighton** [comment]
@rikhepworth Yes that should have been fixed in #193.

**Comment by iainbrighton** [comment]
@rikhepworth given that we're only talking about enabling VHDX support for Gen1 VMs, the flag could go in one of two places:

1. In the media's `CustomData` definition
2. In the node's/VM's configuration data

My gut feel is that this setting should go into the media's definition. My reasoning is that the partitioning of the VHDX file determines whether it supports a Gen1 (MBR) vs Gen2 (UEFI). If you have a GPT partitioned disk that won't work on a Gen1 VM.

Here's an example of what I propose:
```powershell
NonNodeData = @{
        Lability = @{
            Media = @(
                @{
                    Id = '2012R2_x64_Standard_EN_Eval_GEN1';
                    Filename = '2012R2_x64_Standard_EN_Eval_GEN1.vhdx';
                    Architecture = 'x64';
                    Uri = 'file://C:\Users\Public\Documents\Hyper-V\Virtual%20Hard%20Disks\2012R2_x64_Standard_EN_Eval_GEN1.vhdx';
                    Checksum = '';
                    Description = 'Custom SYSPREP''d GENERATION 1 Windows Server 2012 R2 Standard 64bit English Evaluation';
                    MediaType = 'VHD';
                    CustomData = @{
                        ## Override the virtual machine generation
                        VMGeneration = 1;
                    }
                }
            )
        }
    }
}
```

**Comment by rikhepworth** [comment]
Hi Iain

I follow your logic on that and I think it makes perfect sense. I’m not able to do the research right now, but I’d want to check if I could use an MBR VHD with a gen 2 vm (I’m just not sure), because I can see that we _might_ want to do that. However, I’d say that was enough of an edge case that your solution would get us enough of the way to where we want to be that I’d quit my foul whinging 😊

Interestingly, doing it in the media (the config for which we are generating centrally in our image factory) gives us some control over what type of VMs are built by our devs, which in turn allows some forced standardisation, which I like.

I should probably show you where we’ve got to sometime, since we’ve made huge leaps in the very short time we’ve been working on this since I found Lability and we couldn’t have achieved anywhere near as much had it not existed!

Cheers

Rik

**Comment by iainbrighton** [comment]
@rikhepworth you can certainly attached a MBR formatted disk to a Gen2 VM, but you won't be able to boot (they might be some hack around)!
