### ISSUE TITLE
Cert issue in v0.19.0

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#382]
Just a heads up that there seems that there's been a change in the Cert details (mainly changing from London to Oxford) which PowerShellGet is complaining about on download which has killed our builds.

![image](https://user-images.githubusercontent.com/6355225/73747025-68d48200-474e-11ea-9ce8-149d5d53cbe6.png)

We can bypass this with `-SkipPublisherCheck` but wanted to flag in case others get this

**Comment by iainbrighton** [comment]
Hi Ryan, the old code signing cert was replaced, but a little while ago now. I’ll take a look. Thanks, Iain
Confidential Communication: This e-mail is intended only for the use of the addressee named above and may be confidential. If you are not the addressee you must not read it and must not use any information contained in nor copy it or inform any person other than Virtual Engine or the addressee of its existence or contents. If you have received this email in error please delete it. It is the responsibility of the recipient to ensure that this message and its attachments are virus free. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Company, its directors or officers unless otherwise specifically stated.

**Comment by iainbrighton** [comment]
On reading that error message in more detail, it does seem correct - the previous cert was registered to the Oxford office, but we relocated the Head Office to London. The message states that this is different to the previously installed module, which is correct!

I think if you’d never had the 0.18.0 release installed, you won’t see the error. However, if it’s a valid certificate, I’m not sure why you’d receive any error?!

Confidential Communication: This e-mail is intended only for the use of the addressee named above and may be confidential. If you are not the addressee you must not read it and must not use any information contained in nor copy it or inform any person other than Virtual Engine or the addressee of its existence or contents. If you have received this email in error please delete it. It is the responsibility of the recipient to ensure that this message and its attachments are virus free. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Company, its directors or officers unless otherwise specifically stated.

**Comment by kilasuit** [comment]
I don't think this is an issue with Lability but an issue with PowerShellGet as raised in https://github.com/PowerShell/PowerShellGet/issues/579 - though I raised it here too for visibility for others that may run into this in the future and be thinking WTF
