### ISSUE TITLE
Get-LabVM doesnt check for the Lability Environment prefix

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#89]
When you have a lab with a prefix like "TLG-" in the EnvironmentPrefix in the Labilty section in the NonNodeData part of the configuration data file this isnt checked in the Get-LabVM function

example configuration data 

```powershell
NonNodeData = @{
        Lability = @{
            EnvironmentPrefix = 'TLG-';
```
Get-LabVM returns the following errors although you can see that Get-VM returns them correctly

![labilityerror1](https://cloud.githubusercontent.com/assets/6355225/14446309/61e91516-004c-11e6-9960-163fc877dbd9.PNG)

It should only be a small addition to the Get-LabVM function to check for this setting in the Configuration Document

**Comment by iainbrighton** [comment]
@kilasuit Yes - this will need fixing. At the moment, the `-ConfigurationData` parameter isn't mandatory on the `*-LabVM` cmdlets. Obviously the prefix information is not available if this isn't passed. Should this be made mandatory? Should we use the prefix if we can find it, otherwise default to the existing behaviour?

**Comment by iainbrighton** [comment]
@kilasuit I beg your pardon - this is definitely a bug!
